language: ruby
cache:
- bundler
install:
- bundle install
rvm:
- 2.0
- 2.1
- 2.2
- 2.3.0
- 2.4.1
notifications:
  email:
    recipients:
    - user.localhost2000@gmail.com
    on_success: change
    on_failure: always
script:
- bundle exec rake default
- gem build sensu-plugins-stackstorm.gemspec
- gem install sensu-plugins-stackstorm-*.gem
deploy:
  provider: rubygems
  api_key:
    secure: VOa8Z+OVR0PTo0Vu2JKc/ID8gwSO7K8KT9HJQHBJsXTialfkQTCt3qhvYu5SU6ZHAk5g7PuFAOOUgAoJjYqLGRdMZnHIG1dwLcPzWOARLgtFE4hxqr923IdOn/QrJQ/8bdYCgpF3LLZAaHt4CCOjIIghB9HrbOeW9CD2ioD2UUY1Mrm22BhMnaKNWbfxYXla80rbEkM5TarGQpIvCZO7gHd5HewHApPlxh5+PjTdaGPPabO/Q1Q38nYXwfKTJoMCDeeGUMjqZiD3lO9mc18SCCl9uY0JQtepacNL5oRM6GIG4Tse+1lmVgZCSO7oIh2Z/jOyCKl/bd3mdpcUQt2KIskJbR+7cdWO6KwwcPIT5CUrkjyT0ut49RK0tsRJKgCZuv5I4ppRb0YVkpHXQNETh4ptO1uccrE9w3PubsfkLSoiuAnBv7X1t3/dZ943GjULm+KNw/uK9ebpcv1WWxLzFFqHOfbU/H7dC9On6Yp1M+COvhBhwRecv3o2yDFHfVwMq0CXv0GS+inachEseiT0N9D3S1wOnmZbBWx1WvGY4p+5XF3lscZcZxZzbCNkusW46OPm7mkwt3koBG7mz8uJgnE0mQgXydGxgJLI7vJ4x2cbohrt3Ktg4VhQN3QfXCwClYW83dwlYor+yRlhclXGiYd4hNSNLOmzGKHXR507QPU=
  gem: sensu-plugins-stackstorm
  on:
    tags: true
    all_branches: true
    rvm: 2.4.1
    repo: userlocalhost/sensu-plugins-stackstorm
addons:
  code_climate:
    repo_token: 
